server:
  port: 9000

spring:
  profiles:
    active: dev
    #include:
      #- swagger

  #app:
  #  message: This is the primary Application Property for ${spring.application.name} specific to DEV

  gerenciador:
    seguranca:
      enable-https:false;

    origin-permitido:
      localhost:9000
  devtools:
      restart:
        enabled: true
      livereload:
        enabled: false #O Cliente Angular vai habilitar

  datasource:
    #type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/gerenciadorfinanceiro?useTimezone=true&serverTimezone=UTC
    username: root
    password: root

  jpa:
    database: mysql
    #show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  jackson:
    date-format: yyyy-MM-dd




#  spring.jackson.deserialization.fail-on-unknown-properties=true

# https://www.baeldung.com/spring-yaml Olhar esse link


