server:
  port: 9000

spring:
  profiles:
    active: dev
    #include:
      #- swagger

  #app:
  #  message: This is the primary Application Property for ${spring.application.name} specific to DEV

  gerenciadorfinanceiro:
    originPermitida: http://localhost:4200 #Referencia ao Angular

    seguranca: enable-https:false #front end a partir de 10:49


  devtools:
      restart:
        enabled: true
      livereload:
        enabled: false #O Cliente Angular vai habilitar

  datasource:
    url: jdbc:mysql://localhost:3306/gerenciadorfinanceiro?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    #show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  #jackson:
  #  date-format: "YYYY-MM-dd"
  #  serialization:
  #    write_dates_as_timestamps: false
  jackson:
    date-format: "dd/MM/yyyy"








#  spring.jackson.deserialization.fail-on-unknown-properties=true

# https://www.baeldung.com/spring-yaml Olhar esse link


