version: '2'
services:
  backend_default-app:
    image: backend_default
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://backend_default-mysql:3306/backend_default?useUnicode=true&characterEncoding=utf8&useSSL=false
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://backend_default-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://backend_default-elasticsearch:9200
    ports:
      - 8080:8080
  backend_default-mysql:
    extends:
      file: mysql.yml
      service: backend_default-mysql
  backend_default-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: backend_default-elasticsearch
  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak
